---
# tasks file for fish

- name: Add 'fish' repository from PPA
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3

- name: Update repositories cache and install 'fish' shell
  apt:
    name: fish
    state: present
    update_cache: yes

- import_tasks: fisher.yml