---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
  - name: ubuntu-2204
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
provisioner:
  name: ansible
  env:
    LOCAL_USER: root
    LOCAL_USER_HOME: /root
verifier:
  name: ansible
  env:
    LOCAL_USER: root
    LOCAL_USER_HOME: /root